name: macos

on:
  workflow_dispatch:
  push:
    branches: [ "master", "dev" ]

env:
  BUILD_TYPE: Release
  OSX_TARGET: "10.15"

jobs:
  skip_check:
    continue-on-error: false
    runs-on: ubuntu-22.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        concurrent_skipping: 'same_content'
        cancel_others: 'true'
        skip_after_successful_duplicate: 'true'
        paths_ignore: '["**/README.md", "**/docs/**", "**/LICENSE.txt", "vcpkg.json", "toolchains/windows/*", "toolchains/ubuntu/*"]'
        do_not_skip: '["workflow_dispatch", "schedule"]'

  build:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    runs-on: macos-12 

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: recursive 

    - name: Update brew
      run: brew update

    - name: Install dependencies 
      run: brew bundle install --file=./toolchains/macos/Brewfile

    - name: Install python mako
      run: pip3 install mako

    - name: Install volk from vendor/volk
      run: |
        cd vendor/volk 
        cmake . -B build -DCMAKE_OSX_DEPLOYMENT_TARGET=${{env.OSX_TARGET}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja
        sudo cmake --build build --config ${{env.BUILD_TYPE}} --target install 

    - name: Configure CMake
      run: cmake . -B ${{github.workspace}}/build-macos -DCMAKE_OSX_DEPLOYMENT_TARGET=${{env.OSX_TARGET}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja

    - name: Build
      run: cmake --build ${{github.workspace}}/build-macos --config ${{env.BUILD_TYPE}} --target dab_plugin

    - name: Upload files (Release)
      uses: actions/upload-artifact@v3
      with:
        name: sdrpp_dab_radio_plugin_macos
        path: ${{github.workspace}}/build-macos/src
