name: x86-ubuntu

on:
  workflow_dispatch:
  push:
    branches: [ "master", "dev" ]

env:
  BUILD_TYPE: Release

jobs:
  skip_check:
    continue-on-error: false
    runs-on: ubuntu-22.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        concurrent_skipping: 'same_content'
        cancel_others: 'true'
        skip_after_successful_duplicate: 'true'
        paths_ignore: '["**/README.md", "**/docs/**", "**/LICENSE.txt", "vcpkg.json", "toolchains/windows/*"]'
        do_not_skip: '["workflow_dispatch", "schedule"]'

  build:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: recursive 
      
    - name: Install packages
      shell: bash
      run: ./toolchains/ubuntu/install_packages.sh
    
    - name: Configure CMake
      shell: bash
      run: cmake -B ${{github.workspace}}/build-ubuntu -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/toolchains/ubuntu/linux-gnu-toolchain.cmake

    - name: Build
      run: ninja -C ${{github.workspace}}/build-ubuntu dab_plugin

    - name: Create package
      shell: sh
      run: ./toolchains/ubuntu/create_package.sh

    - name: Upload files (Release)
      uses: actions/upload-artifact@v3
      with:
        name: sdrpp_dab_radio_plugin_ubuntu
        path: ${{github.workspace}}/plugin_package
    
